name: 'json_dynamic_widget_plugin_rive'
description: 'A plugin to the JSON Dynamic Widget to provide Rive support to the widgets'
homepage: 'https://github.com/peiffer-innovations/json_dynamic_widget_plugin_rive'
version: '3.0.2+3'

environment: 
  sdk: '>=2.19.0 <4.0.0'

analyzer: 
  exclude: 
    - 'lib/generated/**'


dependencies: 
  child_builder: '^2.0.1'
  flutter: 
    sdk: 'flutter'
  json_class: '^2.1.5+2'
  json_dynamic_widget: '^6.0.1+1'
  json_theme: '^5.0.0+2'
  logging: '^1.1.1'
  meta: '^1.8.0'
  rive: '^0.10.1'
  uuid: '^3.0.7'

false_secrets: 
  - 'example/web/index.html'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
