name: json_dynamic_widget_plugin_rive
description: A plugin to the JSON Dynamic Widget to provide Rive support to the widgets
homepage: https://github.com/peiffer-innovations/json_dynamic_widget_plugin_rive

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  child_builder: ^2.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  json_class: ^2.0.0+2
  json_dynamic_widget: ^3.1.1
  json_theme: ^3.1.0
  logging: ^1.0.2
  meta: ^1.7.0
  rive: ^0.7.33
  uuid: ^3.0.4
  websafe_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
