name: 'json_dynamic_widget_plugin_rive'
description: 'A plugin to the JSON Dynamic Widget to provide Rive support to the widgets'
homepage: 'https://github.com/peiffer-innovations/json_dynamic_widget_plugin_rive'
version: '3.0.1+3'

environment: 
  sdk: '>=2.17.0 <3.0.0'

analyzer: 
  exclude: 
    - 'lib/generated/**'


dependencies: 
  child_builder: '^2.0.0+3'
  flutter: 
    sdk: 'flutter'
  json_class: '^2.1.2+8'
  json_dynamic_widget: '^5.0.2+4'
  json_theme: '^4.0.0+6'
  logging: '^1.0.2'
  meta: '^1.7.0'
  rive: '^0.9.0'
  uuid: '^3.0.6'

false_secrets: 
  - 'example/web/index.html'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


ignore_updates: 
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'term_glyph'
  - 'vector_math'
