name: 'json_dynamic_widget_plugin_rive'
description: 'A plugin to the JSON Dynamic Widget to provide Rive support to the widgets'
homepage: 'https://github.com/peiffer-innovations/json_dynamic_widget_plugin_rive'
version: '4.0.0'

environment:
  sdk: '>=2.19.0 <4.0.0'

analyzer:
  exclude:
    - 'lib/generated/**'

dependencies:
  child_builder: '^2.0.1'
  flutter:
    sdk: 'flutter'
  json_class: '^3.0.0+4'
  json_dynamic_widget: '^7.0.0+2'
  json_theme: '^6.2.6+1'
  logging: '^1.2.0'
  meta: '^1.9.1'
  rive: '^0.11.16'
  uuid: '^4.0.0'

false_secrets:
  - 'example/web/index.html'

dev_dependencies:
  build_runner: '^2.3.3'
  flutter_lints: '^2.0.3'
  flutter_test:
    sdk: 'flutter'
  json_dynamic_widget_codegen: '^1.0.0'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
