name: json_dynamic_widget_plugin_rive
description: A plugin to the JSON Dynamic Widget to provide Rive support to the widgets
homepage: https://github.com/peiffer-innovations/json_dynamic_widget_plugin_rive

version: 2.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  child_builder: ^2.0.0+3
  flutter:
    sdk: flutter
  json_class: ^2.1.2+4
  json_dynamic_widget: ^4.1.0
  json_theme: ^3.3.1
  logging: ^1.0.2
  meta: ^1.7.0
  rive: ^0.8.4
  uuid: ^3.0.6

false_secrets:
  - example/web/index.html

dev_dependencies:
  flutter_test:
    sdk: flutter
